### ISSUE TITLE
Matplotlib-venn loading fails when loading Huracanpy

### ISSUE THREAD

**Issue by stella-bourdin** [Huracan-project/huracanpy#22] opened 2024-06-19 14:47 UTC
When installing huracanpy via `pip install huracanpy` in an environment where matplotlib-venn was not installed beforehand (?), and then opening python and importing huracanpy, a error is raised that matplotlib-venn is not found. 
Current fix = going back and running `pip install matplotlib-venn`

**Comment by leosaffin** [comment] 2024-06-20 09:38
I think this was just due to using "--pre" for the install. There is a 1.0.0-alpha that can get installed and cause errors (https://pypi.org/project/matplotlib-venn/#history). It's the only way I can reproduce this error

**Comment by stella-bourdin** [comment] 2024-06-20 09:44
So using the `--pre` when installing huracanpy forces it for every sub-package being installed on the way? 
I removed the option from the README in any case

**Comment by leosaffin** [comment] 2024-06-20 09:55
> So using the --pre when installing huracanpy forces it for every sub-package being installed on the way?

Seems to be the case. That's not how I would expect (or want) it to work either. Maybe there's some other options we can specify to make it work better.

**Comment by leosaffin** [comment] 2024-06-20 10:26
Didn't mean to close this, sorry.

**Closed** 2024-11-21 15:14 UTC
